### ISSUE TITLE
The source code of ASLI (WWW2020)

### ISSUE THREAD

**Issue by crayonyon** [Mehrab-Tanjim/DynamicRec#1]
I' m interested in your paper "Attentive Sequential Models of Latent Intent for Next Item Recommendation", which is released in the WWW 2020. Could you please provide the source code of this paper for me? 
I would like to do some further research on your work, and your source code will be of great benefit to me. My email is linxiaolin.mine@qq.com.
I will very appreciate it for your generosity!  Thank you~

**Comment by Mehrab-Tanjim** [comment]
Hi, thanks for reaching out. You can easily reproduce the results based on the description of the architecture from the paper.

**Update** Reproduction of the results and a TF implementation is now available at: https://github.com/Mehrab-Tanjim/ASLI

**Comment by crayonyon** [comment]
all right, thank you very much anyway！

**Comment by Mehrab-Tanjim** [comment]
Hi, I reproduced the results and provided the code for it. It is available here: https://github.com/Mehrab-Tanjim/ASLI

sorry, it took this long, I couldn't work on this due to other commitments. I hope this is still helpful!
